apiVersion: v1 
kind:  Namespace
metadata: 
    name: mynamespace      #namespace name
    labels:
        name: mynamespace
--- 
apiVersion: v1 
metadata: 
     name: nginx-pod
     namespace: mynamespace    #pod is created inside mynamespace
kind:  Pod
spec: 
     containers:
      - name: nginx-container 
        image: nginx
        ports:
          - containerPort: 80
---
apiVersion: v1
metadata: 
    name: ci-service
    namespace: mynamespace    #service  is created inside mynamespace  namespace
kind: Service
spec: 
    selector:
        app: podci
    type: ClusterIP
    ports:
      - protocol: TCP 
        port: 80 
        targetPort: 80